/**
 * The browser seal for connection credentials (plan B6, design 7.2, E3).
 *
 * AES-GCM 256 with one key per browser profile, generated by WebCrypto as
 * non-extractable and kept as a CryptoKey in IndexedDB database
 * `FinlityConnectorKeys` (store `keys`, id `connector-v1`), apart from the
 * `PortfolioApp` database. The key is never exported, and never written to
 * localStorage or to the SQLite database, so a saved or downloaded .db file
 * holds only ciphertext. Each seal uses a fresh random 96-bit IV and binds the
 * connection id as additional data, so a value moved to another connection
 * does not open (the server binds its Fernet value the same way).
 *
 * Unseal never generates a key: without the original one (site data cleared,
 * another browser, a server `fernet:` value) it throws `SealUnreadable`,
 * which the composites record as `reconnect_needed`. When IndexedDB or
 * WebCrypto itself fails it throws `SealUnavailable` instead, which leaves the
 * connection as it is (the failure may pass). Threat model: this
 * protects the exported file and casual inspection, not a script running in
 * the page, which could call decrypt itself; CSP and textContent-only DOM
 * rules are the XSS defence.
 *
 * Plaintext lives only in the caller's memory for one v2 request. Nothing
 * here logs, and no error carries the plaintext or the sealed value.
 *
 * Imported only by the connection composites (and the connections feature),
 * never by the main entry, so it stays in a lazy chunk.
 */

import { SEALED_IV_BYTES, isSealedValue, type CredentialVault } from './credential-vault';

export const KEY_DB_NAME = 'FinlityConnectorKeys';
const KEY_DB_VERSION = 1;
const KEY_STORE = 'keys';
const KEY_ID = 'connector-v1';
const ALGORITHM = { name: 'AES-GCM', length: 256 } as const;

/** The sealed value cannot be opened here; the connection needs Reconnect. */
export class SealUnreadable extends Error {
  constructor() {
    super('The saved credential cannot be read in this browser.');
    this.name = 'SealUnreadable';
  }
}

/** The key store or WebCrypto is unusable here (private mode, old browser). */
export class SealUnavailable extends Error {
  constructor() {
    super('This browser cannot keep connection credentials.');
    this.name = 'SealUnavailable';
  }
}

function subtle(): SubtleCrypto {
  const s = globalThis.crypto?.subtle;
  if (!s) throw new SealUnavailable();
  return s;
}

function openKeyDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const factory = globalThis.indexedDB;
    if (!factory) {
      reject(new SealUnavailable());
      return;
    }
    const request = factory.open(KEY_DB_NAME, KEY_DB_VERSION);
    request.onupgradeneeded = (): void => {
      if (!request.result.objectStoreNames.contains(KEY_STORE)) {
        request.result.createObjectStore(KEY_STORE);
      }
    };
    request.onsuccess = (): void => resolve(request.result);
    request.onerror = (): void => reject(new SealUnavailable());
    request.onblocked = (): void => reject(new SealUnavailable());
  });
}

/**
 * Whether the key database may exist. Where `databases()` is available this
 * avoids opening (and so creating) it; without it, unseal opens the database,
 * which can create an empty one but never generates a key.
 */
async function keyDbExists(): Promise<boolean> {
  const factory = globalThis.indexedDB;
  if (!factory) throw new SealUnavailable();
  if (typeof factory.databases !== 'function') return true;
  let names: (string | undefined)[];
  try {
    names = (await factory.databases()).map((d) => d.name);
  } catch {
    throw new SealUnavailable();
  }
  return names.includes(KEY_DB_NAME);
}

function storedKey(db: IDBDatabase): Promise<CryptoKey | null> {
  return new Promise((resolve, reject) => {
    const request = db.transaction(KEY_STORE, 'readonly').objectStore(KEY_STORE).get(KEY_ID);
    request.onsuccess = (): void => resolve(isKey(request.result) ? request.result : null);
    request.onerror = (): void => reject(new SealUnavailable());
  });
}

/** Store `candidate` unless a key is already there (another tab won); return the one kept. */
function keepFirstKey(db: IDBDatabase, candidate: CryptoKey): Promise<CryptoKey> {
  return new Promise((resolve, reject) => {
    const tx = db.transaction(KEY_STORE, 'readwrite');
    const keys = tx.objectStore(KEY_STORE);
    let kept = candidate;
    const read = keys.get(KEY_ID);
    read.onsuccess = (): void => {
      if (isKey(read.result)) kept = read.result;
      else keys.put(candidate, KEY_ID);
    };
    tx.oncomplete = (): void => resolve(kept);
    tx.onerror = (): void => reject(new SealUnavailable());
    tx.onabort = (): void => reject(new SealUnavailable());
  });
}

const isKey = (value: unknown): value is CryptoKey =>
  typeof value === 'object' &&
  value !== null &&
  (value as CryptoKey).type === 'secret' &&
  (value as CryptoKey).algorithm?.name === ALGORITHM.name;

let pendingKey: Promise<CryptoKey> | null = null;

/**
 * The browser's connector key, created once: non-extractable AES-GCM 256,
 * usable only to encrypt and decrypt. Concurrent calls in a tab share one
 * creation, and a key another tab stored first wins. Rejects with
 * SealUnavailable when IndexedDB or WebCrypto cannot be used.
 */
export function getOrCreateKey(): Promise<CryptoKey> {
  pendingKey ??= createOrRead().finally(() => {
    pendingKey = null;
  });
  return pendingKey;
}

async function createOrRead(): Promise<CryptoKey> {
  const db = await openKeyDb();
  try {
    const existing = await storedKey(db);
    if (existing) return existing;
    const candidate = await subtle().generateKey(ALGORITHM, false, ['encrypt', 'decrypt']);
    return await keepFirstKey(db, candidate);
  } finally {
    db.close();
  }
}

/** The stored key, or null when there is none (never creates one). */
async function existingKey(): Promise<CryptoKey | null> {
  if (!(await keyDbExists())) return null;
  const db = await openKeyDb();
  try {
    return await storedKey(db);
  } finally {
    db.close();
  }
}

function toBase64(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function fromBase64(text: string): Uint8Array<ArrayBuffer> {
  const binary = atob(text);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

const additionalData = (connectionId: string): Uint8Array<ArrayBuffer> =>
  new TextEncoder().encode(connectionId);

/** Seal `plaintext` for `connectionId`: `wc1:<iv>:<ciphertext>`, both standard base64. */
export async function seal(connectionId: string, plaintext: string): Promise<string> {
  const key = await getOrCreateKey();
  const iv = globalThis.crypto.getRandomValues(new Uint8Array(SEALED_IV_BYTES));
  const cipher = await subtle().encrypt(
    { name: ALGORITHM.name, iv, additionalData: additionalData(connectionId) },
    key,
    new TextEncoder().encode(plaintext)
  );
  const sealed = `wc1:${toBase64(iv)}:${toBase64(new Uint8Array(cipher))}`;
  if (!isSealedValue(sealed)) throw new SealUnavailable();
  return sealed;
}

/**
 * Open a sealed value for `connectionId`. SealUnreadable for anything this
 * browser cannot open: not a `wc1:` value (a server `fernet:` value), no key
 * here, another connection's value, or a changed ciphertext. SealUnavailable
 * when IndexedDB or WebCrypto itself fails, which may pass.
 */
export async function unseal(connectionId: string, value: string): Promise<string> {
  if (!isSealedValue(value)) throw new SealUnreadable();
  const [, ivText, cipherText] = value.split(':') as [string, string, string];
  // The key store or WebCrypto failing is SealUnavailable and passes through:
  // it may work on the next try, so it must not cost the connection.
  const cryptoApi = subtle();
  const key = await existingKey().catch((error: unknown) => {
    throw error instanceof SealUnavailable ? error : new SealUnavailable();
  });
  if (!key) throw new SealUnreadable();
  let plain: ArrayBuffer;
  try {
    plain = await cryptoApi.decrypt(
      {
        name: ALGORITHM.name,
        iv: fromBase64(ivText),
        additionalData: additionalData(connectionId),
      },
      key,
      fromBase64(cipherText)
    );
  } catch {
    throw new SealUnreadable();
  }
  try {
    return new TextDecoder('utf-8', { fatal: true }).decode(plain);
  } catch {
    throw new SealUnreadable();
  }
}

/** The CredentialVault the composites use. One key serves every connection, so delete keeps nothing. */
export const webCryptoVault: CredentialVault = {
  seal,
  unseal,
  delete: () => Promise.resolve(),
};
